### ISSUE TITLE
Schematics?

### ISSUE THREAD

**Issue by kzyapkov** [MHEtLive/ESP32-MINI-KIT#3]
I am integrating the MiniKit in a device with weird power supply, which would be much simpler if I had the schematics. Is there a protection diode for USB power? What are the 3v3 LDO specs, can it be fed with 12V?

But yeah, just release the schematics. All other devkits do it.

**Comment by MHEtLive** [comment]
The LDO 4.75V ≤ VIN ≤ 12V,but notice that 0 ≤ IOUT ≤ 800mA ,

**Comment by sschueller** [comment]
I believe this is the schematic
![epe4dgj](https://user-images.githubusercontent.com/1180107/37556716-20616fd8-29fa-11e8-9542-c7f0d03da3b5.jpg)

**Comment by MHEtLive** [comment]
Yes.@sschueller   And you can find somthing new-update from here about mh-et live minikit.
http://forum.mhetlive.com/topic/8/mh-et-live-minikit-for-esp32

**Comment by kakaducsy** [comment]
@MHEtLive 
I think schematic is good, but not flexible. This Kit only use with USB cable, cannot use with batteries

**Comment by pierremolinaro** [comment]
This is NOT the schematic :
  - MH ET LIVE minikit has only one push button, the schematics shows two;
  - IO2 builtin led is active high, the schematic shows an active low led.

**Comment by MuchammadSobrun** [comment]
That is the schematic of MH-ET LIVE ESP32 Development Board WiFi + Bluetooth. not minikit.

**Comment by pierremolinaro** [comment]
Okay, however the schematic's title is MH-ET LIVE ESP32-MINIKIT…

And where can we find the minikit schematic ?

Pierre

**Comment by ASTEG012** [comment]
It is very difficult to find relatable documentation for the MiniKit and that what you find is not always very clear. I am still not sure if the MiniKit development board can be powered with external 5V as the pin layout plan suggest. 

Did any body has experiences with this board?

**Comment by ricardoquesada** [comment]
it is possible to power the minikit with 5v (i'm doing that)... but regardless of that, I'm still interested in the minikit schematic... any update @MHEtLive ?

**Comment by kekersdev** [comment]
> I believe this is the schematic
> ![epe4dgj](https://user-images.githubusercontent.com/1180107/37556716-20616fd8-29fa-11e8-9542-c7f0d03da3b5.jpg)

It looks lite there is an error in the auto program/reset circuit (bottom left corner): DTR is connected to both bases and RTS to both emitters but instead it should be connected like this 
![image](https://user-images.githubusercontent.com/27924939/130619576-c869329d-deab-4022-b35f-23aa52395a5b.png)

i.e. DTR and RTS should be swapped on the right side
![image](https://user-images.githubusercontent.com/27924939/130620273-b67ee843-3d80-4b7b-b1b7-39b65e5f5411.png)
