### ISSUE TITLE
These examples are for ESP8266 not ESP32

### ISSUE THREAD

**Issue by CEStanley58** [MHEtLive/ESP32-MINI-KIT#6]
In the cpp file for OLED, D0, D1, D2, D3, D4, D5, D6, D7 and D8 have no corollary in ESP32 but do exist in ESP8266. Why are these examples in ESP32 repository?

**Comment by MHEtLive** [comment]
In the demo ino file,the pin has changed. Like this .

SSD1306  display(0x3c, 21, 22);
// SH1106 display(0x3c, D3, D5);

**Comment by CEStanley58** [comment]
The issue remains. Invalid conversion from int to gpio_num_t. Not a big issue, just add "GPIO_NUM_" in front of 21 and 22.
